# The function is executed for all of the elements within the list, and a new list is produced
# with elements generated by the given function for every item.
# The map() method is used to square all the entries in a list in this example
# Code to calculate the square of each number of a list using the map() function
# Method1
'''numbers_list = [2, 4, 5, 1, 3, 7, 8, 9, 10]
squared_list = list(map(lambda num: num ** 2, numbers_list))
print('Square of each number in the given list:', squared_list)'''

# Method2
number_list = [12, 67, 98, 34, 43]
res = []
for i in number_list:
    res.append(i*2)
print(res)

